name: social-graph-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: SocialGraphService
  image: lewisrye/social-network-microservices
  name: social-graph-service
  ports: 
  - containerPort: 9090
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "500m"

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config
