name: home-timeline-redis

ports:
  - port: 6379
    targetPort: 6379

container:
  args: 
  - /social-network-microservices/config/redis.conf
  image: library/redis
  imageVersion: 7.4.1
  name: home-timeline-redis
  ports: 
  - containerPort: 6379
  resources:
    limits:
      cpu: "1000m"

configMaps:
  - name: redis.conf
    mountPath: /social-network-microservices/config/redis.conf
    value: redis
