name: media-memcached

ports:
  - port: 11211
    targetPort: 11211

container:
  image: library/memcached
  imageVersion: 1.6.33
  name: media-memcached
  ports: 
  - containerPort: 11211

jaeger:
  agentHost: "jaeger-agent"
  agentPort: 6831
  samplerType: "const"
  samplerParam: 1
  logSpans: true
  queueSize: 100
  bufferFlushInterval: 10
  disabled: false

configMaps:
  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config