name: media-frontend

ports:
  - port: 8081
    targetPort: 8080

container:
  image: lewisrye/media-frontend
  imageVersion: xenial
  name: media-frontend
  ports: 
  - containerPort: 8081
  env:
  - name: fqdn_suffix
    value: ".{{ .Release.Namespace }}.svc.cluster.local"

configMaps:
  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config

  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

# affinity
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: "In"
          values:
          - "minikube"

# tolerations     
tolerations:
- key: "monitoring"
  operator: "Equal"
  value: "enabled"
  effect: "NoSchedule"

jaeger:
  agentHost: "jaeger-agent"
  agentPort: 6831
  samplerType: "const"
  samplerParam: 1
  logSpans: true
  queueSize: 100
  bufferFlushInterval: 10
  disabled: false